#!/usr/bin/bash
#!/usr/bin/sh
#$ -S /usr/bin/bash
#$ -cwd
#$ -l s_vmem=100G
#$ -l mem_req=100G

#please change the files of each percentile of each condition
grep -v sca unique_heat_5per.csv | sed "s/^.//g" | nl | sed "s/.1.,/.1,/g" | sed "s/^   /SNP_/g" | sed "s/\t/,/g" | sed "s/SNP_  /SNP_/g" | sed "s/SNP_ /SNP_/g" > unique_heat_5per_list.txt

mkdir -p Heat_TajimaD_5percentile_uniq

for i in `cat unique_heat_5per_list.txt`
do
  echo "$i" > line.tmp
  ID=`cut -f 1 -d "," line.tmp`
  CHR=`cut -f 2 -d "," line.tmp`
  STR=`cut -f 3 -d "," line.tmp | awk '{print $0}'`
  END=`cut -f 3 -d "," line.tmp | awk '{print $0+5000}'`  # Get a range of 5000bp
  
  # Split and process every 1000bp
  for ((j=0; j<5; j++))
  do
    SUBSTR=$((STR + j * 1000))  # Start position
    SUBEND=$((SUBSTR + 999))    # End position
    
     # Match the filename with the FASTA header
    FILENAME="${ID}_$((j+1)).fasta"
    HEADER_NAME="${FILENAME%.fasta}"  # Remove .fasta
    echo "Processing: $FILENAME with range $SUBSTR-$SUBEND on chromosome $CHR"
    echo -e ">$HEADER_NAME" > Heat_TajimaD_5percentile_uniq/"$FILENAME"
    
    # Extract the corresponding sequence and write it to the file
    grep -A1 "$CHR" unfold_genome.fasta | cut -c "$SUBSTR"-"$SUBEND" | tail -1 >> Heat_TajimaD_5percentile_uniq/"$FILENAME"
  done
done
